config/routes.rb
Rails.application.routes.draw do

  resources :users, only: [:index, :show, :create, :edit, :destroy, :update]
  get 'users/results' => 'users#results'
  get '/signup' => 'users#new'
  post '/signup' => 'sessions#create'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  get '/results/:id' => 'results#show', :as => :result

  get '/redirect' => 'static_pages#redirect'

  namespace :api, defaults: {format: "json"} do
    resources :twitter_accounts, only: [:index, :create]
    resources :tweets, only: [:index, :create]
    post "/authenticate" => 'authentication#sign_in'
  end

    root 'static_pages#home'

  get '/auth/:provider/callback', to: 'static_pages#home'
  
  require 'sidekiq/web' 
    mount Sidekiq::Web => '/sidekiq'

end

app/views/shared/_flash.html.erb
<div class="container">
  <% flash.each do |name, msg| %>
    <% if msg.is_a?(String) %>
      <div class="alert alert-<%= flash_class_name(name) %>" role="alert">
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span>
        <span class="sr-only">Close</span>
        </button>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/shared/_navigation.html.erb
<nav class= "navbar navbar-inverse navbar-fixed-top ">
<div class="container-fluid">
  <div class="navbar-left">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
      <i class="fa fa-bars"></i>
    </button>
    <a class="navbar-brand" href="/">
      <%= image_tag("https://s3-us-west-1.amazonaws.com/socialyze/graph.png") %>
    </a>
  </div>
  <div class="collapse navbar-collapse" id="myNavbar">
  <% if logged_in? %>
    <ul class="nav navbar-nav navbar-right">
      <li class="dropdown" id ="nav-user-avatar">
          <a href="" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><%= current_user.name %>
          <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to("Dashboard", user_path(current_user)) %></li>
            <li><%= link_to "Account Info", edit_user_path(current_user), :remote => true, "data-toggle" => "modal", "data-target" => "#edit-user" %></li>
            <li><%= link_to 'Log out', logout_path, method: :delete %></li>
          </ul>
      </li>
    </ul>
  <% else %>
    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to "Log in", login_path, :class => "btn btn-social", :id => "white-text", :remote => true, "data-toggle" => "modal", "data-target" => "#log-in" %></li>
    </ul>
    <% end %>
  </div>
</div>
</nav>

<div class="modal fade" id="log-in" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h2 class="modal-title text-center" id="myModalLabel"><i class="fa fa-2x fa-sign-in"></i></h2>
      </div>
      <div class="modal-body">
    <%= simple_form_for :login, :url => login_path, :method => :post do |f| %>

    <%= f.input :email, placeholder: 'Enter your email' %>

    <%= f.input :password, placeholder: "Your password" %>

    <%= f.button :submit, "Log in", class: "btn btn-large btn-primary center-block" %>

  <% end %>
      </div>
    </div>
  </div>
</div>

<% if @current_user %>
<div class="modal fade" id="edit-user" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h2 class="modal-title text-center" id="myModalLabel"><i class="fa fa-2x fa-sign-in"></i></h2>
      </div>
      <div class="modal-body">
        <%= simple_form_for (@current_user) do |f| %>

          <%= f.input :name, placeholder: 'Your Name' %>

          <%= f.input :email, placeholder: 'Your Email Address' %>

          <%= f.input :password, placeholder: "Create a password" %>

          <%= f.input :password_confirmation, placeholder: "Verify Password" %>

          <%= f.button :submit, "Lets Go", :class => "btn btn-primary center-block" %>
        <% end %>
        
        <br>

        <p class="text-center">Not happy? <%= link_to "Delete Your Account", @current_user, :url => user_path(@current_user), method: :delete, data: {confirm: "Are you sure you want to go?"} %></p>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/shared/_signup.html.erb
<%if @user != nil %>
<div class="modal fade" id="sign-up" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h2 class="modal-title text-center" id="myModalLabel"><i class="fa fa-3x fa-user-plus"></i></h2>
      </div>
      <div class="modal-body">
        <div class="user-form">
          <%= simple_form_for @user, :url => users_path, :method => :post do |f| %>

          <%= f.input :name, placeholder: 'Your Name' %>

          <%= f.input :email, placeholder: 'Your Email Address' %>

          <%= f.input :password, placeholder: "Create a password" %>

          <%= f.input :password_confirmation, placeholder: "Verify Password" %>

          <%= f.button :submit, "Lets Go", :class => "btn btn-primary center-block" %>

          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
<% end %>